### ISSUE TITLE
bad request, no acceptable assets even though asset set to "visual" or "analytic"

### ISSUE THREAD

**Issue by rbavery** [tyson-swetnam/porder#45]
I'm working with a Departmental license but I get this error code for the following order:

```
porder order --name "Punjab Burns c" --idlist "/home/rave/tana-spin/waves/kelsey_order/idlist-punjabac" --item "PSScene4Band" --bundle "analytic"

Failed with response: Bad request
Order request resulted in no acceptable assets. Likely due to lack of permissions.
```

This also happens if I change the asset to "visual".

I have a ticket open with Planet support to see if it is an issue on their end but just in case I thought I'd open one here in case anyone has any thoughts on why this is occurring.

Here's my idlist (I renamed with ".txt" to be able to upload to github)
[idlist-punjabac.txt](https://github.com/tyson-swetnam/porder/files/5241847/idlist-punjabac.txt)

**Comment by rbavery** [comment]
I made sure that the order only has 500 lines as well, to not hit the max limit.

**Comment by samapriya** [comment]
Hi @rbavery 
Wondering if you left out the file extension on purpose, the idlist file path should be a complete file path with .csv at the end it cannnot read all files in a folder but just a single file could you try that instead

**Comment by rbavery** [comment]
Ah it looks like an extension is required even though it was a csv. Thanks @samapriya ! The text file didn't have an extension because I had to use the linux `split` tool to divide a 4000 line file into many 500 line files.

**Comment by samapriya** [comment]
@rbavery 
porder has an idsplit function you should look into it, it splits based on number of lines
