### ISSUE TITLE
unexpected behavior of porder idlist - returning empty file

### ISSUE THREAD

**Issue by tillmann123456** [tyson-swetnam/porder#46]
Hi, 
I'm using porder idlist in code looping over mulitple locations to download imagery. While doing that, the command suddenly started returning empty lists, and evidently stopped searching through the Planet library. The same is now the case when entering the porder idlist command directly in the terminal, independent of the geography or time range I use. Other commands like porder quota work as expected. Any ideas?
Thanks a lot!

**Comment by tillmann123456** [comment]
In case it's useful for anyone else: I still don't know what caused the error, but a reinstall of Python and GDAL made the downloads work again.

**Comment by samapriya** [comment]
Apologies for the delay in responding to this, since this was ad hoc am closing this issue, GDAL and shapely changes sometimes mess up the behavior of this tool so I am glad it is working again

**Comment by tillmann123456** [comment]
I encountered the issue again now. It seems to depend on the planet account I use for logging in with the "planet init" command. With one account, it works, with the other, it doesn't. Any ideas, other than having to go through a gdal reinstallation?

**Comment by samapriya** [comment]
Hi @tillmann123456 
This is a harder issue to track down since it is account specific and I have been unable to replicate at my end. My guess would be to also check if specific accounts have quota available.
