### ISSUE TITLE
Suggestion: filter by acquisition time

### ISSUE THREAD

**Issue by tillmann123456** [tyson-swetnam/porder#47]
Hi Samapriya, 

I'd have a suggestion for an additional filter criterion for the idlist command, namely the time of day at which the image was acquired. Or is there perhaps a way to do this already?

Thanks a lot, 

Tillmann

**Comment by samapriya** [comment]
Hi @tillmann123456 
This issue has now been integrated as an enhancement and you can pass date and time together for the search function/idlist command. For example all of these are valid. This feature is available in version 0.8.1 onwards

```
2021-01-01
or
2021-01-01T09:10:10
or
2021-01-01T14:12
```

**Comment by tillmann123456** [comment]
Great, thanks. Do I understand correctly that this would not allow me yet to search in one go for, say, all images taken between 9am and 11am local time on any given day in 2020? That would be useful for my application, but perhaps that's a rather limited use case.

**Comment by samapriya** [comment]
Yes you can the time filter applies to both start and end dates

So --start 2021-03-26T09:00 --end 2021-03-26T11:00 gets you there based on local time
